language: node_js
sudo: false
node_js:
  - '10'
  - '8'
  - '6'
install:
  - yarn
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - tsc && nyc --reporter=text-lcov ava dist/test > coverage.json
after_success:
  - ./cc-test-reporter after-build -t lcov -i coverage.json --exit-code $TRAVIS_TEST_RESULT