name: Code Coverage

on:
  push: {}
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run Coverage
        run: npm run coverage

      - name: Generate Coverage Report
        run: npx nyc report --reporter=text-summary

      - name: Annotate Coverage Report
        id: coverage
        run: npx nyc report --reporter=text | tee coverage.txt

      - name: Surface Coverage Annotations
        run: |
          echo "::group::Coverage Report"
          cat coverage.txt
          echo "::endgroup::"

          if grep -q "ERROR" coverage.txt; then
            echo "::error file=coverage.txt::Coverage failed."
          fi